services:
  frontend:
    image: prajakta989/devhubweb:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - devops-net

  backend:
    image: prajakta989/devhub:latest
    ports:
      - "5000:3000"
    environment:
    - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
    - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    networks:
      - devops-net

  mongo:
    image: mongo

    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - devops-net

volumes:
  mongo-data:

networks:
  devops-net: