version: "3.8"

services:
  frontend:
    image: prajakta989/devhubweb:latest
    networks:
      - devops-net
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    image: prajakta989/devhub:latest
    networks:
      - devops-net
    ports:
      - "5000:3000"
    env_file:
      - ./DevHub/.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    networks:
      - devops-net
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: